<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

/**
 * Autogenerated with this command
 * php dmt make:a provider @providername
 */

class @providername extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
