<?php

/**
 *
 * Autogenerated with this command
 *
 * php dmt make:a controller @controllername
 *
 *
 * No sympathy for the devil; keep that in mind. Buy the ticket, take the ride...
 * and if it occasionally gets a little heavier than what you had in mind, well...
 * maybe chalk it off to forced conscious expansion:
 *      Tune in, freak out, get beaten.
 *
 *
 */

namespace App\Controllers;

use App\Console\TUI;
use League\CLImate\CLImate;

class @controllername
{

    /**
     *  @controllername
     *  GLOBAL VARIABLES
     *
     *  NAME              EXAMPLE
     *  --------------|--------------------------------
     *
     *  $climate      =>  self::$climate->out('blah');
     *  $globalWidth  =>  $x = self::$globalWidth;
     *
     */

    public static $climate;
    public static $globalWidth  = 60;


    /**
     *
     * CONSTANTS
     *
     */

    const PALETTE_TEMPLATE = resource_path('palettes/template_table.json');


    /**
     * constructStatic
     *
     * @phreakname static constructor
     *
     * @return void
     */
    public static function constructStatic()
    {
        setlocale(LC_ALL, 'en_US.UTF8');
        self::$climate = new CLImate;
    }


    /**
     * getAttr
     *
     * Get an Attribute
     *
     * @param  string $value
     *
     * @return string
     */
    public function getAttr($value = "")
    {
        $value = ($value !== "" ? "zero" : "one");

        return $value;
    }

}

@controllername::constructStatic();
