<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use App\Console\TUI;
use League\CLImate\CLImate;

/**
 * Autogenerated with this command
 * php dmt make:a provider WallpaperProvider
 */

class WallpaperProvider extends ServiceProvider
{
    public $cli;

    public $job = false;

    /**
     * Register services.
     *
     * @return void
     */
    public function register(): void
    {
        // $this->cli = new CLImate();
        // $this->cli->out('wallpaper service provider register');
        // $this->cli->br();
    }

    public function buildWallpaper(): void
    {
        // $this->cli->out('build wallpaper');
        // $this->cli->br();
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot(): void
    {
        // $this->cli->out('wallpaper service provider boot');
        if($this->job !== false){
            $this->buildWallpaper();
        }
    }

    public function setJob($job){
        $this->job = $job;
    }

    public function getJob(){
        return $this->job;
    }
}
